substitutions:
  devicename: powermon-workdesk
  friendly_devicename: Work Desk Power Monitor

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: yes

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".lan"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_devicename}"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API & OTA Updates
api:
  password: !secret api_password
ota:
  password: !secret ota_password

# Enable Web Server.
web_server:
  port: 80

# Enable MQTT
mqtt:
  broker: mqtt.lan
  username: !secret mqtt_user
  password: !secret mqtt_password
  birth_message:
    topic: $devicename/status
    payload: online
  will_message:
    topic: $devicename/status
    payload: offline

# Ensure Time Sync with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Toronto

# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_devicename}: ESP Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_devicename}: ESP Device"

sensor:
  - platform: wifi_signal
    name: "${friendly_devicename}: WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    update_interval: 30s
    current:
      name: "${friendly_devicename}: Current"
      accuracy_decimals: 1
      id: current
      device_class: current
    voltage:
      name: "${friendly_devicename}: Voltage"
      accuracy_decimals: 1
      id: voltage
      device_class: voltage
    power:
      name: "${friendly_devicename}: Power"
      accuracy_decimals: 1
      id: power
      device_class: power
    energy:
      name: "${friendly_devicename}: Energy"
      accuracy_decimals: 1
      id: energy
      device_class: energy
  - platform: total_daily_energy
    name: "${friendly_devicename}: Total Daily Energy"
    icon: "mdi:counter"
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy

switch:
  - platform: gpio
    name: "${friendly_devicename}: Relay Status"
    internal: True
    icon: mdi:power-socket-us
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin: GPIO13
